////// AUTH
export const AUTH_AUTH_LOADING = 'AUTH_AUTH_LOADING'
export const AUTH_AUTH_LOADED = 'AUTH_AUTH_LOADED'
export const AUTH_RELOADE_PAGE = 'AUTH_RELOADE_PAGE'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_USER_LOADED = 'AUTH_USER_LOADED'
export const AUTH_USER_EXPIRED = 'AUTH_USER_EXPIRED'
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS'
////// END-AUTH
////// ACCOUNT
export const ACCOUNT_ACCOUNT_LOADED = 'ACCOUNT_ACCOUNT_LOADED'
export const ACCOUNT_BIODATA_LOADED = 'ACCOUNT_BIODATA_LOADED'
export const ACCOUNT_PENDIDIKAN_LOADED = 'ACCOUNT_PENDIDIKAN_LOADED'
export const ACCOUNT_KETERAMPILAN_LOADED = 'ACCOUNT_KETERAMPILAN_LOADED'
export const ACCOUNT_KELUARGA_LOADED = 'ACCOUNT_KELUARGA_LOADED'
export const ACCOUNT_RIWAYAT_KERJA_LOADED = 'ACCOUNT_RIWAYAT_KERJA_LOADED'
export const ACCOUNT_PERTANYAAN_LOADED = 'ACCOUNT_PERTANYAAN_LOADED'
////// END-ACCOUNT
////// ACCOUNT
export const JOB_LIST_LOADED = 'JOB_LIST_LOADED'
export const JOB_DETAIL_LOADED = 'JOB_DETAIL_LOADED'
export const JOB_APPLY_LOADED = 'JOB_APPLY_LOADED'
export const JOB_SAVE_LOADED = 'JOB_SAVE_LOADED'
////// END-ACCOUNT